### ISSUE TITLE
Viabackwards fixed version does not work on 1.7.10 client version.

### ISSUE THREAD

**Issue by Seanoo1** [xIsm4/SternalBoard#16]
I downloaded from https://github.com/xIsm4/SternalBoard/releases/tag/%23ViaVersion-Cut
but still it is cut off on 16 characters on 1.7.10 client.
I use paper 1.17.1 server.

**Comment by xIsm4** [comment]
Could u send me your logs please?

**Comment by Seanoo1** [comment]
what log? screenshot?

**Comment by xIsm4** [comment]
> what log? screenshot?

Ur server logs, so i can debug what's happening

**Comment by Seanoo1** [comment]
https://paste.gg/p/seanoo/12e44e37fea04fff8b3ebbcac9ed4565

**Comment by xIsm4** [comment]
> https://paste.gg/p/seanoo/12e44e37fea04fff8b3ebbcac9ed4565

[ViaVersion] ERROR IN Protocol1_16_4To1_17 IN REMAP OF WINDOW_CONFIRMATION (0x07)
--
  | [21:46:33 INFO]: Seanoo lost connection: Internal Exception: io.netty.handler
  
  (As i said up u should use ProtocolSuport it's more stable)

**Comment by Seanoo1** [comment]
no that is because of themis anti cheat. I reported just before

**Comment by xIsm4** [comment]
> no that is because of themis anti cheat. I reported just before

I know, what im trying to say u it that ViaVersion/VR/Backwards it's not that stable, my preference it's ProtocolSupport on 1.17.1x

**Comment by xIsm4** [comment]
Btw, ill try to fix it on 1.7x i didn't excepted that anyone will use that version with 1.17.1x
